# TODO : Fix this to pull an automatic tensorflow image
FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /app/src
COPY ./jobs/train.py /app/

EXPOSE 7000

CMD ["python", "train.py"]